var sampleDataOfStudents = [
    {"id":"1","fullName":"Phạm Hồng Phong","emailAddress":"conan1988@yahoo.com","phoneNumber":"0988.102.888","homeTown":"Hà Nội","gender":"Nam"}, 
    {"id":"2","fullName":"Trần Ngọc Linh","emailAddress":"doitruong23@hotmail.com","phoneNumber":"0912.203.885","homeTown":"Nam Định","gender":"Nữ"}, 
    {"id":"3","fullName":"Trần Minh Vương","emailAddress":"vuongtm_hp@gmail.com","phoneNumber":"0913.993.311","homeTown":"Hải Phòng","gender":"Nữ"}, 
    {"id":"4","fullName":"Nguyễn Trung Thành","emailAddress":"mu_reddelvin124@gmail.com","phoneNumber":"0904.177.324","homeTown":"Thái Nguyên","gender":"Nam"}, 
    {"id":"5","fullName":"Lê Minh Ngọc","emailAddress":"ngoclm.hp@gmail.com","phoneNumber":"0904.637.858","homeTown":"Hải Phòng","gender":"Nữ"}, 
    {"id":"6","fullName":"Trần Bình An","emailAddress":"binhantran@yahoo.com.vn","phoneNumber":"0842.448.799","homeTown":"Bắc Giang","gender":"Nam"}, 
    {"id":"7","fullName":"Vũ Hoàng Yến","emailAddress":"hoangyen.87@gmail.com","phoneNumber":"0983.125.383","homeTown":"Ninh Bình","gender":"Nữ"}, 
    {"id":"8","fullName":"Trương Minh Khôi","emailAddress":"langtumuadong@hotmail.com","phoneNumber":"0987.385.999","homeTown":"Hà Nội","gender":"Nam"}, 
    {"id":"9","fullName":"Nguyễn Ngọc Minh","emailAddress":"minhnn.90@gmail.com","phoneNumber":"0914.833.632","homeTown":"Hà Nam","gender":"Nam"}, 
    {"id":"10","fullName":"Phạm Bích Ngọc","emailAddress":"ngocpham.bio@gmail.com","phoneNumber":"0906.235.827","homeTown":"Thanh Hóa","gender":"Nữ"}, 
    {"id":"11","fullName":"Nguyễn Thành Nam","emailAddress":"namnguyen12894@gmail.com","phoneNumber":"0915.323.884","homeTown":"Bắc Ninh","gender":"Nam"}, 
    {"id":"12","fullName":"Đỗ An Bình","emailAddress":"peace-world.0912@yahoo.com","phoneNumber":"0839.468.681","homeTown":"Lạng Sơn","gender":"Nam"}, 
    {"id":"13","fullName":"Đặng Minh Phương","emailAddress":"peony1208@hotmail.com","phoneNumber":"0912.330.918","homeTown":"Thái Bình","gender":"Nữ"}, 
    {"id":"14","fullName":"Vũ Thuận Yến","emailAddress":"thuanyen.vu.90@gmail.com","phoneNumber":"0916.900.918","homeTown":"Hải Dương","gender":"Nam"}, 
    {"id":"15","fullName":"Đào Thị Thu Nga","emailAddress":"ngadtt.vinh@gmail.com","phoneNumber":"0842.546.813","homeTown":"Nghệ An","gender":"Nữ"}, 
    {"id":"16","fullName":"Nguyễn Tuấn Minh","emailAddress":"onggiaxebus@hotmail.com","phoneNumber":"0917.469.222","homeTown":"Hà Tĩnh","gender":"Nam"}, 
    {"id":"17","fullName":"Phạm Khánh An","emailAddress":"khanhan_tb@gmail.com","phoneNumber":"0983.199.004","homeTown":"Thái Bình","gender":"Nữ"}, 
    {"id":"18","fullName":"Bùi Nam Phương","emailAddress":"namphuong96@gmail.com","phoneNumber":"0842.547.629","homeTown":"Vĩnh Phúc","gender":"Nữ"}, 
    {"id":"19","fullName":"Đặng Nhật Minh","emailAddress":"minhmuoi68@yahoo.com","phoneNumber":"0904.173.922","homeTown":"Điện Biên","gender":"Nam"}, 
    {"id":"20","fullName":"Nguyễn Hoàng Minh","emailAddress":"minhmupmip@gmail.com","phoneNumber":"0914.356.244","homeTown":"Lào Cai","gender":"Nam"}
];